# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
    ]
